// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: choice.proto

#include "choice.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

namespace choice {
class ChoiceDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Choice> _instance;
} _Choice_default_instance_;
}  // namespace choice
static void InitDefaultsChoice_choice_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::choice::_Choice_default_instance_;
    new (ptr) ::choice::Choice();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::choice::Choice::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Choice_choice_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsChoice_choice_2eproto}, {}};

void InitDefaults_choice_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_Choice_choice_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_choice_2eproto[1];
constexpr ::google::protobuf::EnumDescriptor const** file_level_enum_descriptors_choice_2eproto = nullptr;
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_choice_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_choice_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::choice::Choice, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::choice::Choice, whowin_),
  PROTOBUF_FIELD_OFFSET(::choice::Choice, hash_),
  PROTOBUF_FIELD_OFFSET(::choice::Choice, choice_),
  PROTOBUF_FIELD_OFFSET(::choice::Choice, status_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::choice::Choice)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::choice::_Choice_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_choice_2eproto = {
  {}, AddDescriptors_choice_2eproto, "choice.proto", schemas,
  file_default_instances, TableStruct_choice_2eproto::offsets,
  file_level_metadata_choice_2eproto, 1, file_level_enum_descriptors_choice_2eproto, file_level_service_descriptors_choice_2eproto,
};

const char descriptor_table_protodef_choice_2eproto[] =
  "\n\014choice.proto\022\006choice\"F\n\006Choice\022\016\n\006WhoW"
  "in\030\001 \001(\t\022\014\n\004hash\030\003 \001(\t\022\016\n\006choice\030\002 \001(\003\022\016"
  "\n\006status\030\004 \001(\tB\'\252\002$Google.Protobuf.Examp"
  "les.AddressBookb\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_choice_2eproto = {
  false, InitDefaults_choice_2eproto, 
  descriptor_table_protodef_choice_2eproto,
  "choice.proto", &assign_descriptors_table_choice_2eproto, 143,
};

void AddDescriptors_choice_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_choice_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_choice_2eproto = []() { AddDescriptors_choice_2eproto(); return true; }();
namespace choice {

// ===================================================================

void Choice::InitAsDefaultInstance() {
}
class Choice::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Choice::kWhoWinFieldNumber;
const int Choice::kHashFieldNumber;
const int Choice::kChoiceFieldNumber;
const int Choice::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Choice::Choice()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:choice.Choice)
}
Choice::Choice(const Choice& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  whowin_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.whowin().size() > 0) {
    whowin_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.whowin_);
  }
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hash().size() > 0) {
    hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
  }
  status_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.status().size() > 0) {
    status_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_);
  }
  choice_ = from.choice_;
  // @@protoc_insertion_point(copy_constructor:choice.Choice)
}

void Choice::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_Choice_choice_2eproto.base);
  whowin_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  choice_ = PROTOBUF_LONGLONG(0);
}

Choice::~Choice() {
  // @@protoc_insertion_point(destructor:choice.Choice)
  SharedDtor();
}

void Choice::SharedDtor() {
  whowin_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Choice::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Choice& Choice::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Choice_choice_2eproto.base);
  return *internal_default_instance();
}


void Choice::Clear() {
// @@protoc_insertion_point(message_clear_start:choice.Choice)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  whowin_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  choice_ = PROTOBUF_LONGLONG(0);
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Choice::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Choice*>(object);
  ::google::protobuf::uint32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string WhoWin = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::Parse32(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("choice.Choice.WhoWin");
        auto str = msg->mutable_whowin();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          object = str;
          str->clear();
          str->reserve(size);
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto len_delim_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(str, ptr, size, ctx);
        ptr += size;
        break;
      }
      // int64 choice = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 16) goto handle_unusual;
        ::google::protobuf::uint64 val;
        ptr = ::google::protobuf::io::Parse64(ptr, &val);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ::google::protobuf::int64 value = val;
        msg->set_choice(value);
        break;
      }
      // string hash = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 26) goto handle_unusual;
        ptr = ::google::protobuf::io::Parse32(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("choice.Choice.hash");
        auto str = msg->mutable_hash();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          object = str;
          str->clear();
          str->reserve(size);
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto len_delim_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(str, ptr, size, ctx);
        ptr += size;
        break;
      }
      // string status = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 34) goto handle_unusual;
        ptr = ::google::protobuf::io::Parse32(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("choice.Choice.status");
        auto str = msg->mutable_status();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          object = str;
          str->clear();
          str->reserve(size);
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto len_delim_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(str, ptr, size, ctx);
        ptr += size;
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Choice::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:choice.Choice)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string WhoWin = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_whowin()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->whowin().data(), static_cast<int>(this->whowin().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "choice.Choice.WhoWin"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 choice = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (16 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &choice_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string hash = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (26 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hash()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->hash().data(), static_cast<int>(this->hash().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "choice.Choice.hash"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string status = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (34 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_status()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->status().data(), static_cast<int>(this->status().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "choice.Choice.status"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:choice.Choice)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:choice.Choice)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Choice::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:choice.Choice)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string WhoWin = 1;
  if (this->whowin().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->whowin().data(), static_cast<int>(this->whowin().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "choice.Choice.WhoWin");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->whowin(), output);
  }

  // int64 choice = 2;
  if (this->choice() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(2, this->choice(), output);
  }

  // string hash = 3;
  if (this->hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hash().data(), static_cast<int>(this->hash().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "choice.Choice.hash");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->hash(), output);
  }

  // string status = 4;
  if (this->status().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status().data(), static_cast<int>(this->status().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "choice.Choice.status");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->status(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:choice.Choice)
}

::google::protobuf::uint8* Choice::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:choice.Choice)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string WhoWin = 1;
  if (this->whowin().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->whowin().data(), static_cast<int>(this->whowin().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "choice.Choice.WhoWin");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->whowin(), target);
  }

  // int64 choice = 2;
  if (this->choice() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(2, this->choice(), target);
  }

  // string hash = 3;
  if (this->hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hash().data(), static_cast<int>(this->hash().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "choice.Choice.hash");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->hash(), target);
  }

  // string status = 4;
  if (this->status().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status().data(), static_cast<int>(this->status().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "choice.Choice.status");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->status(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:choice.Choice)
  return target;
}

size_t Choice::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:choice.Choice)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string WhoWin = 1;
  if (this->whowin().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->whowin());
  }

  // string hash = 3;
  if (this->hash().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hash());
  }

  // string status = 4;
  if (this->status().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->status());
  }

  // int64 choice = 2;
  if (this->choice() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->choice());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Choice::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:choice.Choice)
  GOOGLE_DCHECK_NE(&from, this);
  const Choice* source =
      ::google::protobuf::DynamicCastToGenerated<Choice>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:choice.Choice)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:choice.Choice)
    MergeFrom(*source);
  }
}

void Choice::MergeFrom(const Choice& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:choice.Choice)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.whowin().size() > 0) {

    whowin_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.whowin_);
  }
  if (from.hash().size() > 0) {

    hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hash_);
  }
  if (from.status().size() > 0) {

    status_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_);
  }
  if (from.choice() != 0) {
    set_choice(from.choice());
  }
}

void Choice::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:choice.Choice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Choice::CopyFrom(const Choice& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:choice.Choice)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Choice::IsInitialized() const {
  return true;
}

void Choice::Swap(Choice* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Choice::InternalSwap(Choice* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  whowin_.Swap(&other->whowin_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  hash_.Swap(&other->hash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  status_.Swap(&other->status_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(choice_, other->choice_);
}

::google::protobuf::Metadata Choice::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_choice_2eproto);
  return ::file_level_metadata_choice_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace choice
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::choice::Choice* Arena::CreateMaybeMessage< ::choice::Choice >(Arena* arena) {
  return Arena::CreateInternal< ::choice::Choice >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
