// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: choice.proto

#ifndef PROTOBUF_INCLUDED_choice_2eproto
#define PROTOBUF_INCLUDED_choice_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3006001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_choice_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_choice_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_choice_2eproto();
namespace choice {
class Choice;
class ChoiceDefaultTypeInternal;
extern ChoiceDefaultTypeInternal _Choice_default_instance_;
}  // namespace choice
namespace google {
namespace protobuf {
template<> ::choice::Choice* Arena::CreateMaybeMessage<::choice::Choice>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace choice {

// ===================================================================

class Choice : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:choice.Choice) */ {
 public:
  Choice();
  virtual ~Choice();

  Choice(const Choice& from);

  inline Choice& operator=(const Choice& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Choice(Choice&& from) noexcept
    : Choice() {
    *this = ::std::move(from);
  }

  inline Choice& operator=(Choice&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Choice& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Choice* internal_default_instance() {
    return reinterpret_cast<const Choice*>(
               &_Choice_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Choice* other);
  friend void swap(Choice& a, Choice& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Choice* New() const final {
    return CreateMaybeMessage<Choice>(nullptr);
  }

  Choice* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Choice>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Choice& from);
  void MergeFrom(const Choice& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Choice* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string WhoWin = 1;
  void clear_whowin();
  static const int kWhoWinFieldNumber = 1;
  const ::std::string& whowin() const;
  void set_whowin(const ::std::string& value);
  #if LANG_CXX11
  void set_whowin(::std::string&& value);
  #endif
  void set_whowin(const char* value);
  void set_whowin(const char* value, size_t size);
  ::std::string* mutable_whowin();
  ::std::string* release_whowin();
  void set_allocated_whowin(::std::string* whowin);

  // string hash = 3;
  void clear_hash();
  static const int kHashFieldNumber = 3;
  const ::std::string& hash() const;
  void set_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_hash(::std::string&& value);
  #endif
  void set_hash(const char* value);
  void set_hash(const char* value, size_t size);
  ::std::string* mutable_hash();
  ::std::string* release_hash();
  void set_allocated_hash(::std::string* hash);

  // string status = 4;
  void clear_status();
  static const int kStatusFieldNumber = 4;
  const ::std::string& status() const;
  void set_status(const ::std::string& value);
  #if LANG_CXX11
  void set_status(::std::string&& value);
  #endif
  void set_status(const char* value);
  void set_status(const char* value, size_t size);
  ::std::string* mutable_status();
  ::std::string* release_status();
  void set_allocated_status(::std::string* status);

  // int64 choice = 2;
  void clear_choice();
  static const int kChoiceFieldNumber = 2;
  ::google::protobuf::int64 choice() const;
  void set_choice(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:choice.Choice)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr whowin_;
  ::google::protobuf::internal::ArenaStringPtr hash_;
  ::google::protobuf::internal::ArenaStringPtr status_;
  ::google::protobuf::int64 choice_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_choice_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Choice

// string WhoWin = 1;
inline void Choice::clear_whowin() {
  whowin_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Choice::whowin() const {
  // @@protoc_insertion_point(field_get:choice.Choice.WhoWin)
  return whowin_.GetNoArena();
}
inline void Choice::set_whowin(const ::std::string& value) {
  
  whowin_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:choice.Choice.WhoWin)
}
#if LANG_CXX11
inline void Choice::set_whowin(::std::string&& value) {
  
  whowin_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:choice.Choice.WhoWin)
}
#endif
inline void Choice::set_whowin(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  whowin_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:choice.Choice.WhoWin)
}
inline void Choice::set_whowin(const char* value, size_t size) {
  
  whowin_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:choice.Choice.WhoWin)
}
inline ::std::string* Choice::mutable_whowin() {
  
  // @@protoc_insertion_point(field_mutable:choice.Choice.WhoWin)
  return whowin_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Choice::release_whowin() {
  // @@protoc_insertion_point(field_release:choice.Choice.WhoWin)
  
  return whowin_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Choice::set_allocated_whowin(::std::string* whowin) {
  if (whowin != nullptr) {
    
  } else {
    
  }
  whowin_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), whowin);
  // @@protoc_insertion_point(field_set_allocated:choice.Choice.WhoWin)
}

// string hash = 3;
inline void Choice::clear_hash() {
  hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Choice::hash() const {
  // @@protoc_insertion_point(field_get:choice.Choice.hash)
  return hash_.GetNoArena();
}
inline void Choice::set_hash(const ::std::string& value) {
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:choice.Choice.hash)
}
#if LANG_CXX11
inline void Choice::set_hash(::std::string&& value) {
  
  hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:choice.Choice.hash)
}
#endif
inline void Choice::set_hash(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:choice.Choice.hash)
}
inline void Choice::set_hash(const char* value, size_t size) {
  
  hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:choice.Choice.hash)
}
inline ::std::string* Choice::mutable_hash() {
  
  // @@protoc_insertion_point(field_mutable:choice.Choice.hash)
  return hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Choice::release_hash() {
  // @@protoc_insertion_point(field_release:choice.Choice.hash)
  
  return hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Choice::set_allocated_hash(::std::string* hash) {
  if (hash != nullptr) {
    
  } else {
    
  }
  hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hash);
  // @@protoc_insertion_point(field_set_allocated:choice.Choice.hash)
}

// int64 choice = 2;
inline void Choice::clear_choice() {
  choice_ = PROTOBUF_LONGLONG(0);
}
inline ::google::protobuf::int64 Choice::choice() const {
  // @@protoc_insertion_point(field_get:choice.Choice.choice)
  return choice_;
}
inline void Choice::set_choice(::google::protobuf::int64 value) {
  
  choice_ = value;
  // @@protoc_insertion_point(field_set:choice.Choice.choice)
}

// string status = 4;
inline void Choice::clear_status() {
  status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Choice::status() const {
  // @@protoc_insertion_point(field_get:choice.Choice.status)
  return status_.GetNoArena();
}
inline void Choice::set_status(const ::std::string& value) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:choice.Choice.status)
}
#if LANG_CXX11
inline void Choice::set_status(::std::string&& value) {
  
  status_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:choice.Choice.status)
}
#endif
inline void Choice::set_status(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:choice.Choice.status)
}
inline void Choice::set_status(const char* value, size_t size) {
  
  status_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:choice.Choice.status)
}
inline ::std::string* Choice::mutable_status() {
  
  // @@protoc_insertion_point(field_mutable:choice.Choice.status)
  return status_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Choice::release_status() {
  // @@protoc_insertion_point(field_release:choice.Choice.status)
  
  return status_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Choice::set_allocated_status(::std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  status_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), status);
  // @@protoc_insertion_point(field_set_allocated:choice.Choice.status)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace choice

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_choice_2eproto
